#!/bin/bash
#
# /etc/rc.d/init.d/namecoind
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions

NAME="namecoind"
PIDFILE="/var/run/$NAME.pid"
APP="/usr/bin/$NAME"
ARGS="-daemon -server -conf=~/.namecoin/namecoin.conf -pid=$PIDFILE"

start() {
        if [ -f $PIDFILE ]; then
                PID=`cat $PIDFILE`
                if [ ! -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                        echo "$NAME already running"
                        failure
                        return 1
                else
                        echo "$NAME pid file exists but process is not running"
                        failure
                        return 1
                fi
        fi

        $APP $ARGS

        if [ $? -eq 0 ];then
                success
        else
                failure
        fi
}

stop() {
        $APP stop

        if [ $? -eq 0 ];then
                success
        else
                failure
        fi
}

status() {
        if [ -f $PIDFILE ]; then
                PID=`cat $PIDFILE`

                if [ ! -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                        echo "$NAME is running"
                else
                        echo "$NAME is not running"
                fi
        else
                echo "$NAME is not running"
        fi
}

case "$1" in
        start)
                start
        ;;
        stop)
                stop
        ;;
        status)
                status
        ;;
        restart)
                stop
                sleep 5
                start
        ;;
        *)
                echo "Usage: <servicename> {start|stop|status|restart"
                exit 1
        ;;
esac